name: my-badges

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: 0 0 1 * *

permissions:
  contents: write

jobs:
  my-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Update badges
        run: npx update-my-badges ${{github.repository_owner}} --compact --size=32
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
